baseURL: "https://devspace.mx"
languageCode: "es-MX"
title: "Comunidad DevSpace"
theme: "novela"
paginate: 8
social:
  github: "https://github.com/devspacemx"
  twitter: "https://twitter.com/devspacemx"
  instagram: "https://instagram.com/devspacemx"
  facebook: "https://facebook.com/DevSpaceMexico"
taxonomies:
  author: authors
enableEmoji: true
languageCode: "es-MX"
defaultContentLanguage: "es"
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  author: DevSpace
  description: "Somos una comunidad de estudiantes que busca desarrollarse de manera profesional y potencializar nuestras soft-skills y hard-skills mediante el aprendizaje colectivo y meetups.
  No solo somos programadores, también invitamos a personas de otros perfiles interesados en el ámbito de tecnológia y emprendimiento. Todos son aceptados siempre y cuando compartan nuestros ideales y valores como comunidad.
  Anímate a formar parte de nosotros!"
  default_image: "/images/preview.png"