baseURL: "https://devspace.mx"
languageCode: "es-MX"
title: "DevSpace"
theme: "novela"
paginate: 8
social:
  github: "https://github.com/DevSpaceMX"
  twitter: "https://twitter.com/DevSpaceMX"
  instagram: "https://instagram.com/devspacemx"
  facebook: "https://facebook.com/DevSpaceMexico"
taxonomies:
  author: authors
enableEmoji: true
